<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSKrficY\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSKrficY/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSKrficY.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerSKrficY\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerSKrficY\srcProdProjectContainer(array(
    'container.build_hash' => 'SKrficY',
    'container.build_id' => '250e63ec',
    'container.build_time' => 1515884421,
));
