<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCaGa3JA\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCaGa3JA/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCaGa3JA.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCaGa3JA\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCaGa3JA\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'CaGa3JA',
    'container.build_id' => 'b30fcd1d',
    'container.build_time' => 1515594500,
));
