<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE6xpa4U\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE6xpa4U/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerE6xpa4U.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerE6xpa4U\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerE6xpa4U\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'E6xpa4U',
    'container.build_id' => '4d2adf21',
    'container.build_time' => 1515888685,
));
