<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSTQZbXx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSTQZbXx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSTQZbXx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSTQZbXx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerSTQZbXx\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'STQZbXx',
    'container.build_id' => '2edf835c',
    'container.build_time' => 1516195655,
));
